---
title: "Replication of Study X  \"How Quick Decisions Illuminate Moral Character\" by Critcher et al. (2013, Social Psychological and Personality Science)"
author: "Emily Han (emh006@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

In original experiment, the study explores how people make trait judgement evaluation, specifically on moral character, of the actor based on how quickly the actor reach to a moral and immoral decision. The study suggests that polarized judgments arise when decisions are made quickly—leading observers to over-attribute actions to internal traits (either pristine or corrupt character). The study matches my research interest in social cognition and in especially how social judgments are made and how does their judgements in turn reflect the prejudices and biases they have. 

In this project, we would replicate the study 1 of the expermient. It would be a 2 (moral outcome: moral vs immoral) x2 (decision speed: quick vs slow) between study where the paritcpant will be either assign to moral or immoral condition and learn how two different actors quickly or slowly they reacheed to their decision. Then they would answer questionare on character evalutions of the two different actors. A challenge for this study lies in controlling for potential order effects (e.g., participants rating on an actor differently based on whether they read the other actor’s scenario first), which may require randomizing the order of stimulus presentation. 

[GitHub Repository](https://github.com/emilyh006/moral_character_exp.git)

[Link to original paper](https://github.com/emilyh006/moral_character_exp/blob/f5df2a9ef2facccf21e1520a3dd4da5ad1a12441/original_paper/Critcher_et_al_2013.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
